<a href="https://colab.research.google.com/github/dante513/Portafolio/blob/main/tienda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importación de datos

In [2]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

#1. Análisis de facturación

# PASO 0: Unir las cuatro tiendas en un solo DataFrame
# Usamos pd.concat() para juntar los datos uno debajo del otro

In [4]:
datos_completos = pd.concat([tienda, tienda2, tienda3, tienda4], ignore_index=True)
datos_completos.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

# PASO 1: Análisis de facturación
# Sumamos todos los valores de la columna 'Precio'

In [5]:
facturacion_total = datos_completos['Precio'].sum()
print(f"La facturación total es de ${facturacion_total}")

La facturación total es de $4403619200.0

# Mostramos el resultado formateado para que sea fácil de leer

In [6]:
print(f"La facturación total de todas las tiendas es: ${facturacion_total:,.2f}")

La facturación total de todas las tiendas es: $4,403,619,200.00

# 2. Ventas por categoría

# PASO 2: Ventas por categoría
# Usamos groupby para agrupar por la columna 'Categoría del Producto'
# Luego seleccionamos la columna 'Precio' y sumamos sus valores

In [8]:
ventas_por_categoria = datos_completos.groupby('Categoría del Producto')['Precio'].sum()
print(ventas_por_categoria)

Categoría del Producto
Artículos para el hogar    5.757980e+07
Deportes y diversión       1.429777e+08
Electrodomésticos          1.324751e+09
Electrónicos               1.660576e+09
Instrumentos musicales     3.487726e+08
Juguetes                   7.360440e+07
Libros                     3.769610e+07
Muebles                    7.576610e+08
Name: Precio, dtype: float64

# Ordenamos los resultados de mayor a menor (descendente)

In [9]:
ventas_por_categoria = ventas_por_categoria.sort_values(ascending=False)
print(ventas_por_categoria)

Categoría del Producto
Electrónicos               1.660576e+09
Electrodomésticos          1.324751e+09
Muebles                    7.576610e+08
Instrumentos musicales     3.487726e+08
Deportes y diversión       1.429777e+08
Juguetes                   7.360440e+07
Artículos para el hogar    5.757980e+07
Libros                     3.769610e+07
Name: Precio, dtype: float64

# Mostramos el resultado en pantalla

In [10]:
print("Ventas totales por categoría:")
print(ventas_por_categoria)

Ventas totales por categoría:
Categoría del Producto
Electrónicos               1.660576e+09
Electrodomésticos          1.324751e+09
Muebles                    7.576610e+08
Instrumentos musicales     3.487726e+08
Deportes y diversión       1.429777e+08
Juguetes                   7.360440e+07
Artículos para el hogar    5.757980e+07
Libros                     3.769610e+07
Name: Precio, dtype: float64

# 3. Calificación promedio de la tienda

# PASO 3: Calificación promedio de la tienda
# Seleccionamos la columna 'Calificación' y usamos .mean() para obtener el promedio

In [11]:
calificacion_promedio = datos_completos['Calificación'].mean()
print(f"La calificación promedio de la tienda es: {calificacion_promedio}")

La calificación promedio de la tienda es: 4.014520402755696

# Mostramos el resultado limitando a 2 decimales para que sea más claro

In [12]:
print(f"La calificación promedio de toda la cadena de tiendas es: {calificacion_promedio:.2f} estrellas sobre 5")

La calificación promedio de toda la cadena de tiendas es: 4.01 estrellas sobre 5

# 4. Productos más y menos vendidos

# PASO 4: Productos más y menos vendidos
# Contamos cuántas veces aparece cada producto en la columna 'Producto'

In [13]:
ventas_por_producto = datos_completos['Producto'].value_counts()
print(ventas_por_producto)

Producto
Mesa de noche                  210
Carrito de control remoto      206
Microondas                     206
Batería                        203
Cama king                      201
Secadora de ropa               200
Modelado predictivo            200
Set de ollas                   200
Cama box                       199
Bloques de construcción        199
Iphone 15                      198
Armario                        197
Pandereta                      197
Balón de baloncesto            197
Bicicleta                      196
Iniciando en programación      195
Smart TV                       192
Refrigerador                   191
Lavavajillas                   189
Cubertería                     189
Guitarra acústica              188
Impresora                      188
Kit de bancas                  188
Vaso térmico                   187
Estufa                         187
TV LED UHD 4K                  187
Cuerda para saltar             186
Mesa de comedor                185
Balón de voleibol              184
Sofá reclinable                182
Silla de oficina               181
Dashboards con Power BI        181
Cubo mágico 8x8                180
Ajedrez de madera              180
Tablet ABXY                    179
Lavadora de ropa               176
Muñeca bebé                    175
Mesa de centro                 175
Dinosaurio Rex                 175
Juego de mesa                  175
Auriculares                    174
Olla de presión                172
Smartwatch                     172
Set de vasos                   169
Sillón                         168
Asistente virtual              167
Ciencia de datos con Python    166
Guitarra eléctrica             165
Mochila                        163
Auriculares con micrófono      158
Celular ABXY                   157
Name: count, dtype: int64

# Obtenemos los 5 primeros (más vendidos) y los 5 últimos (menos vendidos)

In [15]:
mas_vendidos = ventas_por_producto.head(5)
menos_vendidos = ventas_por_producto.tail(5)

# Mostramos los resultados en pantalla

In [20]:
print(" TOP 5 PRODUCTOS MÁS VENDIDOS:")
print(mas_vendidos)
print("-" * 30) # Esto solo imprime una línea separadora
print("TOP 5 PRODUCTOS MENOS VENDIDOS:")
print(menos_vendidos)

 TOP 5 PRODUCTOS MÁS VENDIDOS:
Producto
Mesa de noche                210
Carrito de control remoto    206
Microondas                   206
Batería                      203
Cama king                    201
Name: count, dtype: int64
------------------------------
TOP 5 PRODUCTOS MENOS VENDIDOS:
Producto
Ciencia de datos con Python    166
Guitarra eléctrica             165
Mochila                        163
Auriculares con micrófono      158
Celular ABXY                   157
Name: count, dtype: int64

# 5. Envío promedio por tienda

# PASO 5: Envío promedio por tienda (Lugar de Compra)
# Agrupamos por ciudad y calculamos el promedio del costo de envío

In [17]:
envio_promedio_ciudad = datos_completos.groupby('Lugar de Compra')['Costo de envío'].mean()
print(envio_promedio_ciudad)

Lugar de Compra
Armenia          22867.857143
Barranquilla     22692.258065
Bogotá           24532.082171
Bucaramanga      26790.055249
Cali             26726.812314
Cartagena        22638.429752
Cúcuta           28597.311828
Inírida          30557.142857
Leticia          25317.605634
Manizales        24948.780488
Medellín         25282.022472
Neiva            27710.000000
Pasto            27801.063830
Pereira          23211.411992
Riohacha         24127.607362
Santa Marta      18752.317881
Soacha           34768.421053
Valledupar       22021.428571
Villavicencio    25100.000000
Name: Costo de envío, dtype: float64

# Ordenamos los resultados de mayor a menor costo

In [18]:
envio_promedio_ciudad = envio_promedio_ciudad.sort_values(ascending=False)
print(envio_promedio_ciudad)

Lugar de Compra
Soacha           34768.421053
Inírida          30557.142857
Cúcuta           28597.311828
Pasto            27801.063830
Neiva            27710.000000
Bucaramanga      26790.055249
Cali             26726.812314
Leticia          25317.605634
Medellín         25282.022472
Villavicencio    25100.000000
Manizales        24948.780488
Bogotá           24532.082171
Riohacha         24127.607362
Pereira          23211.411992
Armenia          22867.857143
Barranquilla     22692.258065
Cartagena        22638.429752
Valledupar       22021.428571
Santa Marta      18752.317881
Name: Costo de envío, dtype: float64

# Mostramos el resultado en pantalla

In [19]:
print("Costo de envío promedio por tienda/ciudad:")
print(envio_promedio_ciudad)

Costo de envío promedio por tienda/ciudad:
Lugar de Compra
Soacha           34768.421053
Inírida          30557.142857
Cúcuta           28597.311828
Pasto            27801.063830
Neiva            27710.000000
Bucaramanga      26790.055249
Cali             26726.812314
Leticia          25317.605634
Medellín         25282.022472
Villavicencio    25100.000000
Manizales        24948.780488
Bogotá           24532.082171
Riohacha         24127.607362
Pereira          23211.411992
Armenia          22867.857143
Barranquilla     22692.258065
Cartagena        22638.429752
Valledupar       22021.428571
Santa Marta      18752.317881
Name: Costo de envío, dtype: float64